easy_admin:
    entities:
        Post:
            class: App\Entity\Post
            form:
                fields: ['title', 'exerpt', 'content', { property: 'imageFile', type: 'vich_image' }, 'author', 'published']
            list:
                fields: ['id', 'title', 'exerpt', 'author', { property: 'dateAdd', type: 'datetime', format: 'd/m/Y' }, 'published']