easy_admin:
    entities:
        Post:
            class: App\Entity\Post
            form:
                fields: ['title', 'exerpt', 'content', 'author', 'thumbnail', 'published']
            list:
#                fields: ['id', 'title', 'exerpt', 'author', { property: 'dateAdd', format: 'd/m/Y' }, 'published']
                fields: ['id', 'title', 'exerpt', 'author', 'published']